---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  driver_config:
    box: ubuntu-14.04
- name: centos-6.5
  driver_config:
    box: centos-6_5

suites:
- name: default
  run_list: ["recipe[sensu_spec::test_client]", "recipe[sensu_spec::extra]", "recipe[minitest-handler]"]
  attributes: {}
- name: server
  run_list: ["recipe[sensu_spec::test_server]", "recipe[minitest-handler]"]
  attributes:
settings:
  parallel: true
